apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: europe-north1-docker.pkg.dev/rentalconnect/imagerepository/frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "300m"          # Request 0.3 vCPUs
            memory: "256Mi"      # Request 256 MB memory
          limits:
            cpu: "500m"          # Limit 0.5 vCPUs
            memory: "512Mi"      # Limit 512 MB memory
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
