apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service
  labels:
    app: listing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing-service
  template:
    metadata:
      labels:
        app: listing-service
    spec:
      containers:
      - name: listing-service
        image: europe-north1-docker.pkg.dev/rentalconnect/imagerepository/listing-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri-secret
              key: MONGO_URI
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: gcp-service-account
              key: service-account.json
        resources:
          requests:
            cpu: "300m"          # Request 0.3 vCPUs
            memory: "256Mi"      # Request 256 MB memory
          limits:
            cpu: "500m"          # Limit 0.5 vCPUs
            memory: "512Mi"      # Limit 512 MB memory
---
apiVersion: v1
kind: Service
metadata:
  name: listing-service
spec:
  selector:
    app: listing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer
