apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: europe-north1-docker.pkg.dev/rentalconnect/imagerepository/search-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri-secret
              key: MONGO_URI
        resources:
          requests:
            cpu: "300m"          # Request 0.3 vCPUs
            memory: "256Mi"      # Request 256 MB memory
          limits:
            cpu: "500m"          # Limit 0.5 vCPUs
            memory: "512Mi"      # Limit 512 MB memory
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: LoadBalancer
