apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
      - name: service-account-secret
      containers:
      - name: user-service
        image: europe-north1-docker.pkg.dev/rentalconnect/imagerepository/user-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-uri-secret
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        resources:
          requests:
            cpu: "300m"          # Request 0.3 vCPUs
            memory: "256Mi"      # Request 256 MB memory
          limits:
            cpu: "500m"          # Limit 0.5 vCPUs
            memory: "512Mi"      # Limit 512 MB memory              
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
