name: CI/CD Pipeline (main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run tests for all services
        run: |
          for dir in ./services/* ./frontend; do
            echo "Running tests in $dir"
            cd $dir
            npm install
            npm test || exit 1
            cd -
          done

  push-images:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH_JSON }}

      - name: Configure Docker to use Google Container Registry
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Images
        run: |
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/frontend ./frontend
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/api-gateway ./services/api-gateway
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/user-service ./services/user-service
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/listing-service ./services/listing-service
          docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/search-service ./services/search-service

          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/frontend
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/api-gateway
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/user-service
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/listing-service
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/search-service

  deploy:
    runs-on: ubuntu-latest
    needs: push-images

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH_JSON }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.22.0

      - name: Configure kubectl for GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --region ${{ secrets.GKE_CLUSTER_REGION }} \
            --project ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/api-gateway-deployment.yaml
          kubectl apply -f k8s/user-service-deployment.yaml
          kubectl apply -f k8s/listing-service-deployment.yaml
          kubectl apply -f k8s/search-service-deployment.yaml
